apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pod
spec:
  containers:
    -name: test-container
    image: redis
    env:
      -name: custom-env-name-in-pod
      valueFrom:
        configMapKeyRef:
          name: gyan-lit-config		<created earlier>
          key: special.key				<created b4>
